apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
  namespace: mywebsite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
        - name: mywebsite
          image: kefifaiez/mywebsite:latest
          ports:
            - containerPort: 80
