---
- name: "Build a container with ansible"
  hosts: localhost
  gather_facts: no

  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: Remove unused Docker images
      command: docker image prune -f
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t kefifaiez/websitefinal:test .

    - name: Push Image to dockerhub
      command: docker push kefifaiez/websitefinal:test

    - name: run container
      command: docker run -d -p 80:80 --name web-container kefifaiez/websitefinal:test

    - name: Afficher un message de terminé
      debug:
        msg: "Toutes les tâches sont terminées avec succès !"