# Utilisez l'image de base que vous souhaitez, par exemple, une image Nginx pour un site web statique.
FROM nginx:latest

# Copiez les fichiers de votre site web dans le répertoire approprié de l'image Nginx.
COPY . /usr/share/nginx/html
